# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChallengeAccepted' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChallengeAccepted
    pod 'Parse'

  target 'ChallengeAcceptedTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ChallengeAcceptedUITests' do
    # Pods for testing
  end

end
